### ISSUE TITLE
doesn't detect 10's more png files

### ISSUE THREAD

**Issue by hmmhmmhm** [eugeneware/png-file-stream#4]
![12](https://user-images.githubusercontent.com/38493722/41817925-71043cd0-77df-11e8-94fd-e65fb0d403fa.png)

mmm...

**Comment by hmmhmmhm** [comment]
Solved... anyway it's not involved this modules.
its related glob-stream issues.

10 more files can be detect like this,
temp_? -> temp_??

**Comment by sanidhya711** [comment]
helped a lot 👍👍
